package com.example.ui.theme

import androidx.compose.runtime.Composable

@Composable
fun isEnglishLanguage(): Boolean {
    return LocalAppLanguage.current == AppLanguage.ENGLISH
}

@Composable
fun tr(trText: String, enText: String): String {
    return if (LocalAppLanguage.current == AppLanguage.ENGLISH) enText else trText
}

fun tr(trText: String, enText: String, isEnglish: Boolean): String {
    return if (isEnglish) enText else trText
}

@Composable
fun String.loc(enText: String): String {
    return if (LocalAppLanguage.current == AppLanguage.ENGLISH) enText else this
}

fun String.loc(enText: String, isEnglish: Boolean): String {
    return if (isEnglish) enText else this
}

@Composable
fun String.trAuto(): String {
    if (LocalAppLanguage.current != AppLanguage.ENGLISH) return this
    val exact = Dictionary[this] ?: Dictionary[this.trim()]
    if (exact != null) return exact
    return translateDynamic(this)
}

fun String.trAuto(isEnglish: Boolean): String {
    if (!isEnglish) return this
    val exact = Dictionary[this] ?: Dictionary[this.trim()]
    if (exact != null) return exact
    return translateDynamic(this)
}

private fun translateDynamic(text: String): String {
    if (text.isBlank()) return text
    var res = text

    // Direct case-insensitive dictionary lookup
    DictionaryLower[res.trim().lowercase()]?.let { return it }

    // Phrase replacements
    for ((trKey, enVal) in PhraseReplacements) {
        if (res.contains(trKey, ignoreCase = true)) {
            val regex = Regex(Regex.escape(trKey), RegexOption.IGNORE_CASE)
            res = regex.replace(res, enVal)
        }
    }

    // Replace remaining Turkish product/word names from Dictionary
    for ((trKey, enVal) in Dictionary) {
        if (trKey.length >= 3 && res.contains(trKey)) {
            res = res.replace(trKey, enVal)
        }
    }

    // Replace remaining Turkish Lira symbol with game currency symbol
    if (res.contains("₳")) {
        res = res.replace("₺", "₳")
    }
    return res
}

private val DictionaryLower: Map<String, String> by lazy {
    Dictionary.mapKeys { it.key.lowercase() }
}

private val PhraseReplacements: List<Pair<String, String>> = listOf(
    "🎉 TEBRİKLER! İlk ticaretiniz başarıyla gerçekleşti!" to "🎉 CONGRATULATIONS! Your first trade was completed successfully!",
    "🎉 TEBRİKLER!" to "🎉 CONGRATULATIONS!",
    "TEBRİKLER!" to "CONGRATULATIONS!",
    "EKONOMİK KRİZ:" to "ECONOMIC CRISIS:",
    "EKONOMİK KRİZ" to "ECONOMIC CRISIS",
    "Ekonomik Kriz Start Aldı!" to "Economic Crisis Started!",
    "Ekonomik Kriz Start Aldı" to "Economic Crisis Started",
    "Şehir pazarlarında kıtlık baş gösterdi." to "Scarcity appeared in city markets.",
    "Devlet Müdahalesi:" to "State Intervention:",
    "Devlet Müdahalesi" to "State Intervention",
    "Çiftçi Sübvansiyonu:" to "Farmer Subsidy:",
    "Çiftçi Sübvansiyonu" to "Farmer Subsidy",
    "Günlük nakit ödülü yalnızca çevrimiçi (online) giriş yapan tüccarlara özeldir! Lütfen giriş yapın." to "Daily cash reward is exclusive to online merchants! Please log in.",
    "Bugünkü günlük nakit ödülünüzü zaten aldınız. Gece 00:00'dan sonra tekrar alabilirsiniz!" to "You have already claimed today's daily cash reward. Available again after midnight (00:00)!",
    "Günlük Online Nakit Ödülü (Gün " to "Daily Online Cash Reward (Day ",
    " (Buluta Yedeklendi)" to " (Backed up to Cloud)",
    "Buluta Yedeklendi" to "Backed up to Cloud",
    "🎁 REHBER ÖDÜLÜ ALINDI!" to "🎁 GUIDE REWARD CLAIMED!",
    "REHBER ÖDÜLÜ ALINDI!" to "GUIDE REWARD CLAIMED!",
    "Ekonomik kriz start aldı" to "Economic crisis started",
    "Ekonomik Kriz Start Aldı" to "Economic Crisis Started",
    "ekonomik kriz start aldı" to "economic crisis started",
    "Ekonomik Kriz" to "Economic Crisis",
    "ekonomik kriz" to "economic crisis",
    "start aldı" to "started",
    "Start Aldı" to "Started",
    "🚨 KRİTİK KITLIK:" to "🚨 CRITICAL SCARCITY:",
    "📉 KRİZ RESESYONU:" to "📉 CRISIS RECESSION:",
    "🚨 KRİZ DARBOĞAZI" to "🚨 CRISIS BOTTLENECK",
    "KRİZ UYARISI:" to "CRISIS WARNING:",
    "canlı müzayedeye çıkarıldı!" to "put up for live auction!",
    "müzayedeye çıkarıldı!" to "put up for auction!",
    "müzayedeye çıkarılamadı." to "could not be put up for auction.",
    "müzayedede teklifiniz geçildi!" to "you were outbid in the auction!",
    "başarıyla ihale havuzuna bağışlandı!" to "successfully donated to tender pool!",
    "ihale havuzuna bağışlandı!" to "donated to tender pool!",
    "Bu teknoloji maksimum seviyeye (5) ulaştı!" to "This technology has reached maximum level (5)!",
    "Maksimum eşzamanlı araştırma sınırına (3) ulaşıldı!" to "Maximum concurrent research limit (3) reached!",
    "Yetersiz Sermaye! Gerekli: ₳" to "Insufficient Capital! Required: ₳",
    "Yetersiz Sermaye! Gerekli: ₳" to "Insufficient Capital! Required: ₳",
    "Yetersiz Elmas! Araştırmayı başlatmak için " to "Insufficient Diamonds! To start research ",
    " 💎 gerekli." to " 💎 required.",
    "🔬 Ar-Ge Araştırması Başlatıldı: " to "🔬 R&D Research Started: ",
    "⚡ Araştırma " to "⚡ Research ",
    " Elmas Harcanarak Hızlandırıldı! 🚀" to " Diamonds Spent to Speed Up! 🚀",
    "🔬 Ar-Ge Tamamlandı! " to "🔬 R&D Complete! ",
    "🔬 AR-GE Araştırması Tamamlandı! Yeni teknoloji ve imkanlar açıldı." to "🔬 R&D Research Complete! New technology and features unlocked.",
    "Baş Mühendis işten çıkarıldı." to "Chief Engineer dismissed.",
    "Satış Sorumlusu işten çıkarıldı." to "Sales Manager dismissed.",
    "Müdür işe alım ücreti yetersiz! Gerekli: ₳" to "Manager hiring fee insufficient! Required: ₳",
    "Müdür işe alım ücreti yetersiz! Gerekli: ₳" to "Manager hiring fee insufficient! Required: ₳",
    " Seviye 1 olarak göreve başladı!" to " started as Level 1!",
    "Disiplin Cezası: " to "Disciplinary Penalty: ",
    " 1 seviye düşürüldü!" to " demoted by 1 level!",
    "Kovuldu: " to "Fired: ",
    " disiplinsizlikten işten atıldı!" to " dismissed due to indiscipline!",
    " Terfi için yetersiz bakiye! Gerekli: ₳" to " Insufficient balance for promotion! Required: ₳",
    " Terfi için yetersiz bakiye! Gerekli: ₳" to " Insufficient balance for promotion! Required: ₳",
    "'e terfi ettirildi! Maaşı ve performansı arttı." to " promoted! Salary and performance increased.",
    "'a terfi ettirildi! Maaşı ve performansı arttı." to " promoted! Salary and performance increased.",
    " tesisiniz inşa edildi!" to " facility constructed!",
    " üretimi başlatıldı!" to " production started!",
    "Yetersiz Bakiye! Şehir için " to "Insufficient Balance! For city ",
    " gerekli." to " required.",
    "Depo Kapasitesi Artırıldı! Yeni Kapasite: " to "Warehouse Capacity Increased! New Capacity: ",
    "Tesis mükemmel durumda, bakıma gerek yok!" to "Facility in excellent condition, no maintenance required!",
    "Bakım için yetersiz bakiye! Gerekli: ₳" to "Insufficient balance for maintenance! Required: ₳",
    "Bakım için yetersiz bakiye! Gerekli: ₳" to "Insufficient balance for maintenance! Required: ₳",
    "Bu tesiste üretim devam ediyor! Lütfen işlemin bitmesini bekleyin." to "Production in progress in this facility! Please wait for completion.",
    " Günlük Vadeli B2B Sözleşme imzalandı!" to " Day Forward B2B Contract signed!",
    "Vadeli sözleşme iptal edildi ve ₳" to "Forward contract cancelled and ₳",
    "Vadeli sözleşme iptal edildi ve ₳" to "Forward contract cancelled and ₳",
    " iade alındı." to " refunded.",
    "Deponuzda teslimat için yeterli (" to "Not enough items in warehouse for delivery (",
    " Ton) ürün yok!" to " Tons)!",
    "Sözleşme teslim edildi! +₳" to "Contract delivered! +₳",
    "Sözleşme teslim edildi! +₳" to "Contract delivered! +₳",
    "Tedarik talebi piyasaya duyuruldu!" to "Supply request announced to market!",
    "Tedarik talebi iptal edildi ve ₳" to "Supply request cancelled and ₳",
    "Tedarik talebi iptal edildi ve ₳" to "Supply request cancelled and ₳",
    "🏢 Sendika Mega Projesine ₳" to "🏢 Syndicate Mega Project contributed ₳",
    "🏢 Sendika Mega Projesine ₳" to "🏢 Syndicate Mega Project contributed ₳",
    " katkı sağlandı!" to "!",
    "Sadece kurucu lider konsorsiyumu feshedebilir!" to "Only the founding leader can dissolve the consortium!",
    "Sohbet alanına mesaj göndermek için konsorsiyum üyesi olmalısınız!" to "You must be a consortium member to send messages to chat!",
    "Sohbet grubuna katılmak için önce bu konsorsiyumda bir tedarikçi slotuna katılmalısınız." to "To join chat group, you must first join a supplier slot in this consortium.",
    "Lütfen şirket adı ve marka adını giriniz" to "Please enter company name and brand name",
    "Lütfen geçerli miktar giriniz" to "Please enter a valid amount",
    "Deponuzda yeterli stok bulunmuyor!" to "Not enough stock in your warehouse!",
    "🎬 Ödüllü reklam tamamlandı! +" to "🎬 Rewarded ad completed! +",
    " 💎 Elmas hesabınıza eklendi." to " 💎 Diamonds added to your account.",
    "Kayıt Başarılı! " to "Registration Successful! ",
    " ile çevrimiçi pazara bağlandınız." to " connected to online market.",
    "Giriş Başarılı! Tekrar hoş geldiniz, " to "Login Successful! Welcome back, ",
    " enflasyonu düşürüldü!" to " inflation reduced!",
    " enflasyonu düşürüldü" to " inflation reduced",
    " enflasyonu artırıldı!" to " inflation increased!",
    " enflasyonu artırıldı" to " inflation increased",
    "Çiftçi Sübvansiyonu: " to "Farmer Subsidy: ",
    " taban fiyattan alındı!" to " bought at base price!",
    " taban fiyattan alındı" to " bought at base price",
    " [Devlet Vergisi %5: -" to " [State Tax 5%: -₳",
    " tarafından satın alındı!" to " purchased this!",
    "🚨 Müzayedede teklifiniz geçildi!" to "🚨 You were outbid in the auction!",
    "📈 Borsa Analisti Toptan Tedarik Etti: " to "📈 Stock Analyst Wholesale Supplied: ",
    "🏗️ Üretim Müdürü: " to "🏗️ Production Manager: ",
    " bütçe dahilinde maksimum kapasiteyle başlatıldı." to " started with max capacity within budget.",
    "Maksimum Halka Açıklık Oranı %40'tır. Daha fazla hisse satılamaz!" to "Maximum Public Float Ratio is 40%. No more shares can be sold!",
    "📈 Ek Hisse Satışı Gerçekleşti! +" to "📈 Additional Share Sale Executed! +",
    " Sermaye Girişi!" to " Capital Inflow!",
    "Geri alınacak miktar mevcut halka açık hisseden fazla olamaz!" to "Buyback amount cannot exceed current public float!",
    "Hisse Geri Alımı için Yetersiz Bakiye! Gerekli: " to "Insufficient Balance for Share Buyback! Required: ",
    "Hisse Geri Alımı için Yetersiz Bakiye! Gerekli: ₳" to "Insufficient Balance for Share Buyback! Required: ₳",
    "Hisse Geri Alımı için Yetersiz Bakiye! Gerekli: ₳" to "Insufficient Balance for Share Buyback! Required: ₳",
    "🏛️ Hisse Geri Alımı Tamamlandı! Yeni Halka Açıklık Oranı: %" to "🏛️ Share Buyback Complete! New Public Float Ratio: %",
    "💰 Temettü Dağıtıldı! Yatırımcılara Ödenen Pay: " to "💰 Dividend Distributed! Amount Paid to Investors: ",
    "Hisse senedi alımı için yetersiz bakiye! Gerekli: ₳" to "Insufficient balance for stock purchase! Required: ₳",
    "Hisse senedi alımı için yetersiz bakiye! Gerekli: ₳" to "Insufficient balance for stock purchase! Required: ₳",
    "Halkın elindeki veya borsa hacmindeki toplam kullanılabilir hisse senedi sınırı aşıldı! Maksimum alınabilir: " to "Total available shares limit exceeded! Maximum available: ",
    "📈 Başarılı! " to "📈 Success! ",
    " hissesi satın alındı (-₳" to " shares bought (-₳",
    " hissesi satın alındı (-₳" to " shares bought (-₳",
    "📉 Satış Başarılı! " to "📉 Sale Successful! ",
    " hissesi satıldı: +₳" to " shares sold: +₳",
    " hissesi satıldı: +₳" to " shares sold: +₳",
    " Nakit Bakiyenize Aktarıldı." to " Transferred to Your Cash Balance.",
    "🌙 Çevrimdışı İlerleme (" to "🌙 Offline Progress (",
    "): Net Bakiye Değişimi: ₳" to "): Net Balance Change: ₳",
    "): Net Bakiye Değişimi: ₳" to "): Net Balance Change: ₳",
    " | Üretim: " to " | Production: ",
    " Adet | Bulut Senkronize Edildi!" to " Units | Cloud Synchronized!",
    " saat " to " hrs ",
    " dk" to " mins",
    " dakika" to " minutes",
    "✨ PARTİ ÜRETİMİ TAMAMLANDI: Standart montaj ve kalite kontrol süresi (" to "✨ BATCH PRODUCTION COMPLETE: Standard assembly and QC time (",
    ") doldu! 1 Parti " to ") expired! 1 Batch of ",
    " depoya aktarıldı (Depo: " to " transferred to depot (Depot: ",
    "). Yeni parti kotaları açıldı." to "). New batch quotas opened.",
    "✨ 1 Parti " to "✨ 1 Batch of ",
    " Üretim Bandından Çıktı! Kalite kontrolden geçerek depoya aktarıldı." to " came off the production line! Passed quality control and transferred to depot.",
    "🏭 TÜM HAMMADDELER TEDARİK EDİLDİ: Yeni parti seri üretim bandına alındı! (" to "🏭 ALL RAW MATERIALS SUPPLIED: New batch sent to assembly line! (",
    " montaj süresi)." to " assembly duration).",
    "🏭 Hammaddeler Tamamlandı! Yeni parti seri üretim bandına alındı." to "🏭 Raw Materials Complete! New batch sent to assembly line.",
    "⚠️ Konsorsiyum Gecikmesi: " to "⚠️ Consortium Delay: ",
    " tedariki aksatıyor ve üretimi yavaşlatıyor!" to " is disrupting supply and slowing down production!",
    "💎 Yetersiz Elmas! Konsorsiyum kurmak için " to "💎 Insufficient Diamonds! To form a consortium, ",
    " elmas gerekiyor." to " diamonds are required.",
    "🔬 Bu Mega Projenin Ar-Ge araştırmasını tamamlamadan konsorsiyum kuramazsınız!" to "🔬 You cannot form a consortium without completing R&D research for this Mega Project!",
    "🏗️ '" to "🏗️ '",
    "' Mega Proje Konsorsiyumu kuruldu! Çevrimiçi veriler senkronize edildi." to "' Mega Project Consortium founded! Online data synchronized.",
    "🔬 Bu Mega Projeye katılabilmek için önce Ar-Ge bölümünde ilgili araştırmayı tamamlamalısınız!" to "🔬 You must first complete the research in R&D to join this Mega Project!",
    "🔬 Bu kotalı tedarik ürünü (" to "🔬 For this quota supply product (",
    ") için Ar-Ge araştırmasını tamamlamalısınız!" to "), you must complete R&D research!",
    "🤝 Konsorsiyuma katıldınız (%" to "🤝 You joined the consortium (%",
    " Hisse). Çevrimiçi olarak canlı senkronize edildi!" to " Share). Live synchronized online!",
    "Deponuzda yeterli " to "Insufficient stock of ",
    " stoku yok!" to " in your warehouse!",
    "🧪 TEST ÜRETİMİ BAŞARILI: Konsorsiyum deposu dolduruldu ve 1 adet test ürünü üretildi! Kurucu üyenin satış kanalını (Borsa/Pazar) belirleyip seri üretime onay vermesi bekleniyor." to "🧪 TEST PRODUCTION SUCCESSFUL: Consortium depot filled and 1 test product produced! Founder must choose sales channel and approve mass production.",
    "🧪 Depo Dolduruldu & Test Ürünü Üretildi! Kurucu üyenin satış kanalını seçip seri üretime onay vermesi gerekiyor." to "🧪 Depot Filled & Test Product Produced! Founder must choose sales channel and approve mass production.",
    "📦 " to "📦 ",
    " Ton " to " Tons of ",
    " konsorsiyum şantiyesine teslim edildi!" to " delivered to consortium construction site!",
    "Darboğaz devir alımı için yeterli paranız yok! (Gerekli: ₳" to "Insufficient funds to take over bottleneck! (Required: ₳",
    "Darboğaz devir alımı için yeterli paranız yok! (Gerekli: ₳" to "Insufficient funds to take over bottleneck! (Required: ₳",
    "⚡ SLA Darboğaz Koruması devreye girdi! Geciken ortağın kotası devralındı." to "⚡ SLA Bottleneck Protection activated! Delayed partner's quota taken over.",
    "Mevcut aşamadaki tüm tedarik kotaları tamamlanmadan sonraki aşamaya geçilemez!" to "Cannot proceed to the next stage until all supply quotas in current stage are completed!",
    "🚀 Mega Proje montajı yeni aşamaya geçti: " to "🚀 Mega Project assembly advanced to new stage: ",
    "⚠️ Konsorsiyumda açık slot/ortak eksikliği var! Seri üretim için tüm kotaların doldurulması gerekir." to "⚠️ There are empty slots/missing partners! All quotas must be filled for mass production.",
    "⚠️ Seri üretimin devam etmesi için ortakların tüm kotaları zamanında teslim etmesi gerekir!" to "⚠️ Partners must deliver all quotas on time for mass production to continue!",
    "Deponuz tamamen dolu! Ürünü teslim almak için depoda boş yer açın." to "Your warehouse is completely full! Make space to receive the product.",
    "🏭 Seri Üretim Başarılı! 1 Adet " to "🏭 Mass Production Successful! 1 Unit of ",
    " üretilerek Konsorsiyum Deposu'na aktarıldı (Depo: " to " produced and transferred to Consortium Depot (Depot: ",
    "⚠️ KURUCU KARARI: Seri üretim hattı " to "⚠️ FOUNDER DECISION: Mass production line ",
    "Üretim DURDURULDU" to "Production HALTED",
    "Üretim DEVAM EDİYOR" to "Production CONTINUING",
    "🚫 '" to "🚫 '",
    "' konsorsiyumdan çıkarıldı. Slot yeni ortaklara açıldı." to "' removed from consortium. Slot opened to new partners.",
    "Konsorsiyum deposunda satılacak hazır ürün bulunmuyor!" to "No ready products in consortium warehouse to sell!",
    "💰 Depo Satışı Tamamlandı! " to "💰 Depot Sale Complete! ",
    " kanalıyla ₳" to " channel ₳",
    " kanalıyla ₳" to " channel ₳",
    " hisse payınız) hesabınıza aktarıldı!" to " your share) transferred to your account!",
    "🤖 İK Otomatik Satış Yönetimi Aktif!" to "🤖 HR Auto-Sell Management Active!",
    "⏸️ İK Otomatik Satış Durduruldu." to "⏸️ HR Auto-Sell Stopped.",
    "🔄 Yeni Seri Üretim Partisi Başlatıldı! Kotalar sıfırlandı, sürekli üretim hattı aktif." to "🔄 New Mass Production Batch Started! Quotas reset, continuous production line active.",
    "Bu partinin kâr payı zaten alındı. Yeni parti başlatarak tekrar kâr payı kazanabilirsiniz." to "Dividend for this batch already claimed. Start a new batch to earn dividend again.",
    "💰 Akıllı Temettü Dağıtımı: ₳" to "💰 Smart Dividend Distribution: ₳",
    "💰 Akıllı Temettü Dağıtımı: ₳" to "💰 Smart Dividend Distribution: ₳",
    " Katkı Hissesi) banka hesabınıza yatırıldı! +" to " Contribution Share) deposited to your bank account! +",
    " Marka İtibarı Puanı!" to " Brand Reputation Points!",
    "Sadece kurucu lider konsorsiyumu feshedebilir!" to "Only the founding leader can disband the consortium!",
    "Konsorsiyum feshedildi. Borsa hissedarlarına hisse bedellerinin %50'si oranında mağduriyet iadesi yapıldı. Ortaklık kesintiniz: ₳" to "Consortium disbanded. 50% refund issued to shareholders. Partnership deduction: ₳",
    "Konsorsiyum feshedildi. Borsa hissedarlarına hisse bedellerinin %50'si oranında mağduriyet iadesi yapıldı. Ortaklık kesintiniz: ₳" to "Consortium disbanded. 50% refund issued to shareholders. Partnership deduction: ₳",
    ", Borsa hisse iadeniz: ₳" to ", Stock refund: ₳",
    ", Borsa hisse iadeniz: ₳" to ", Stock refund: ₳",
    "🚪 '" to "🚪 '",
    "' kotasından ayrıldınız. Slot açık duruma getirildi." to "' quota abandoned. Slot made available.",
    "' konsorsiyumundan ayrıldınız." to "' consortium left.",
    "Sohbet alanına mesaj göndermek için konsorsiyum üyesi olmalısınız!" to "You must be a consortium member to send messages to chat!",
    "Sohbet grubuna katılmak için önce bu konsorsiyumda bir tedarikçi slotuna katılmalısınız!" to "You must join a supplier slot in this consortium before joining the chat group!",
    "Lütfen şirket adı ve marka adını giriniz" to "Please enter company name and brand name",
    "Lütfen geçerli miktar giriniz" to "Please enter a valid quantity",
    "Deponuzda yeterli stok bulunmuyor!" to "Insufficient stock in your warehouse!",
    "Yalnızca kayıtlı kullanıcılar için" to "Only for registered users",
    " tesisiniz inşa edildi!" to " facility built!",
    " üretimi başlatıldı!" to " production started!",
    "Yetersiz Bakiye! Şehir için " to "Insufficient Balance! Required for city: ",
    " gerekli." to " required.",
    "(Boş: " to "(Empty: ",
    " Ton)" to " Tons)",
    "Aktif Tesisler (" to "Active Facilities (",
    "Birim: " to "Unit: ",
    "SON DAKİKA: Trakya ve İç Anadolu'da zirai don uyarısı! Tarım emtiaları yükselişte." to "BREAKING: Agricultural frost warning in Thrace and Central Anatolia! Agricultural commodities on the rise.",
    "KÜRESEL İKLİM: Kuraklık tahıl rekoltesini etkiliyor! Buğday ve un fiyatları hareketlendi." to "GLOBAL CLIMATE: Drought affects grain yield! Wheat and flour prices are active.",
    "MÜJDE: Avrupa ve Körfez ülkeleriyle yeni ticaret koridoru açıldı. İhracat hacmi artıyor." to "GOOD NEWS: New trade corridor opened with Europe and Gulf countries. Export volume is growing.",
    "TURİZM REKORU: Akdeniz ve Ege kıyılarına rekor turist akını! Gıda ve hizmet tüketimi katlandı." to "TOURISM RECORD: Record tourist influx to Mediterranean and Aegean coasts! Food and service consumption folded.",
    "TCMB RAPORU: Merkez Bankası para piyasalarında likidite dengeleme adımı attı." to "CBRT REPORT: Central Bank took a liquidity balancing step in money markets.",
    "YÜKSELİŞ: Sanayi üretim endeksi beklentileri aştı! İmalat sektöründe canlılık sürüyor." to "RISE: Industrial production index exceeded expectations! Vitality in manufacturing sector continues.",
    "KÜRESEL LOJİSTİK: Navlun ve konteyner maliyetleri güncellendi, iç pazar üretimi avantaj kazandı." to "GLOBAL LOGISTICS: Freight and container costs updated, domestic production gained advantage.",
    "SANAYİ HAMLESİ: Yeşil fabrika ve güneş enerjisi yatırımlarına sıfır faizli kredi desteği." to "INDUSTRIAL MOVE: Zero-interest loan support for green factory and solar energy investments.",
    "AR-GE & SAVUNMA: İleri teknoloji çip ve batarya üretiminde stratejik alım anlaşması." to "R&D & DEFENSE: Strategic purchase agreement in high-tech chip and battery production.",
    "İHRACAT ŞAMPİYONU: Otomotiv ve beyaz eşya sektörü Avrupa pazarında yeni rekor kırdı." to "EXPORT CHAMPION: Automotive and white goods sector broke a new record in European market.",
    "PİYASA DENGESİ: Anadolu ticaret hatlarında sevkiyatlar kesintisiz sürüyor." to "MARKET BALANCE: Shipments continue uninterrupted in Anatolian trade routes.",
    "BORSA FLAŞ: " to "EXCHANGE FLASH: ",
    " prim yaptı!" to " gained premium!",
    "PİYASA DİP: " to "MARKET DIP: ",
    " fiyatı geriledi, üreticiler için ucuz hammadde fırsatı!" to " price dropped, cheap raw material opportunity for manufacturers!",
    "TCMB FAİZİ: Politika Faizi %" to "CBRT INTEREST: Policy Rate %",
    " seviyesinde." to " level.",
    "Piyasalar açıldı. Son dakika gelişmeleri bekleniyor..." to "Markets opened. Waiting for breaking developments...",
    "AKTİF KONSORSİYUM ÜRÜNLERİ BEKLENİYOR..." to "WAITING FOR ACTIVE CONSORTIUM PRODUCTS...",
    " - Hammadde maliyetleri +%" to " - Raw material costs +%",
    " arttı!" to " increased!",
    "⚠️ KRİTİK KITLIK: Konsorsiyumlarda en çok " to "⚠️ CRITICAL SCARCITY: Procurement crisis in consortiums most for ",
    " hammaddelerinde tedarik krizi yaşanıyor!" to " raw materials!",
    "EKONOMİ BOĞA: Tüketici talebi ve şirket kârlılıkları zirvede! Lüks tüketim yükselişte." to "ECONOMY BULL: Consumer demand and corporate profits at peak! Luxury consumption on the rise.",
    "PİYASA ZİRVEDE: Enflasyon baskısına karşı TCMB faiz ve likidite tedbirlerini sıkılaştırıyor." to "MARKET AT PEAK: CBRT tightens interest and liquidity measures against inflationary pressure.",
    "RESESYON DÖNGÜSÜ: Temel gıda ve enerji emtiaları güvenli liman olmaya devam ediyor." to "RECESSION CYCLE: Basic food and energy commodities continue to be safe havens.",
    "TARİHİ ALIM DÖNEMİ: Emtia fiyatları dipte, tesis yatırımı ve stok toplamak için büyük fırsat." to "HISTORICAL BUYING PERIOD: Commodity prices at bottom, great opportunity for facility investment and stock gathering.",
    "TOPARLANMA DÖNEMİ: Borsa İstanbul ve emtia piyasalarında güven indexi hızla yükseliyor." to "RECOVERY PERIOD: Confidence index in Borsa Istanbul and commodity markets is rising rapidly.",
    "TOPARLANMA DÖNEMİ: Borsa İstanbul ve emtia piyasalarında güven endeksi hızla yükseliyor." to "RECOVERY PERIOD: Confidence index in Borsa Istanbul and commodity markets is rising rapidly.",
    "TR HABER: " to "TR NEWS: ",
    "Ödül Hazır! (Al)" to "Reward Ready! (Claim)",
    "Ödül:" to "Reward:",
    "Bakiye:" to "Balance:",
    "Stok:" to "Stock:",
    "Depoda Hazır" to "Ready in Depot",
    "Depo Müdürü Ayarlıyor" to "Warehouse Manager Preparing",
    "Kilitli Birim Fiyat:" to "Locked Unit Price:",
    "Toplam Değer:" to "Total Value:",
    "Birim Fiyat:" to "Unit Price:",
    "Mevcut Bakiye:" to "Current Balance:",
    "Mevcut Bakiye" to "Current Balance",
    "Pazar Hacmi" to "Market Volume",
    "İlanlarınız" to "Your Listings",
    "Tedarik Talepleri" to "Supply Requests",
    "Vadeli B2B Sözleşmeleri" to "Futures B2B Contracts",
    "Sözleşmeyi Karşıla" to "Fulfill Contract",
    "İptal Et" to "Cancel",
    "Talep Aç" to "Create Request",
    "Satış İlanı Oluştur" to "Create Sales Listing",
    "İlanı Pazara Koy" to "Publish Listing",
    "Yeni Sözleşme" to "New Contract",
    "Tüm Tier'lar" to "All Tiers",
    "Tüm Tesisler" to "All Facilities",
    "Birim Üretim Maliyeti:" to "Unit Production Cost:",
    "Tahmini Üretim Süresi:" to "Est. Production Time:",
    "Maksimum Üretim Limiti:" to "Max Production Limit:",
    "Üretim Miktarı (Adet)" to "Production Quantity (Units)",
    "Üretim Miktarı (Ton)" to "Production Quantity (Tons)",
    "Üretimi Başlat" to "Start Production",
    "TESİSİ TASFİYE ET" to "LIQUIDATE FACILITY",
    "Tasfiye Edilebilir Nakit:" to "Cash Recoverable:",
    "Geri Ödeme Oranı:" to "Refund Rate:",
    "YENİ TESİS KUR" to "BUILD NEW PLANT",
    "Tüm Şehirlerde Ara..." to "Search All Cities...",
    "TESİS KUR" to "BUILD PLANT",
    "YATIRIM YAP" to "INVEST",
    "Nüfus:" to "Population:",
    "Bölge:" to "Region:",
    "Ekonomik Çarpan:" to "Economic Multiplier:",
    "KREDİ ÇEK & ÖDE" to "TAKE & REPAY LOAN",
    "VADELİ MEVDUAT HESABI" to "FIXED TERM DEPOSIT ACCOUNT",
    "Mevcut Kredi Borcu:" to "Current Loan Debt:",
    "Geri Ödeme Yap" to "Make Repayment",
    "Kredi Çek" to "Take Loan",
    "Mevduat Yatır" to "Deposit Money",
    "Mevduat Çek" to "Withdraw Deposit",
    "Eşzamanlı Araştırma" to "Concurrent Research",
    "Seviye İlerlemesi" to "Level Progress",
    "Kalan Süre" to "Time Remaining",
    "HIZLANDIR" to "SPEED UP",
    "Maliyet" to "Cost",
    "Gerekli Seviye" to "Required Level",
    "ARAŞTIR" to "RESEARCH",
    "Yönetici İşe Al" to "Hire Director",
    "Görevden Al" to "Dismiss",
    "Otomatik Satış" to "Auto-Sell",
    "OTOMATİK SATIŞ: AÇIK" to "AUTO-SELL: ON",
    "OTOMATİK SATIŞ: DURDURULDU" to "AUTO-SELL: STOPPED",
    "OTOMATİK SATIŞ MÜDÜRÜ İŞE AL" to "HIRE AUTO-SELL MANAGER",
    "Stok Değeri" to "Stock Value",
    "Merkez Depo" to "Central Depot",
    "TÜCCAR İSMİNİ DEĞİŞTİR" to "CHANGE TRADER NAME",
    "DEPO LOKASYONUNU DEĞİŞTİR" to "RELOCATE WAREHOUSE",
    "DİL SEÇİMİ / LANGUAGE" to "LANGUAGE SELECTION",
    "TÜCCAR PROFİLİ" to "TRADER PROFILE",
    "AYLIK SIRALAMA" to "MONTHLY STANDINGS",
    "TİCARET ODALARI" to "CHAMBERS OF COMMERCE",
    "BİST VE HALKA ARZ" to "BIST & PUBLIC OFFERINGS",
    "Net Değer:" to "Net Worth:",
    "Enflasyon:" to "Inflation:",
    "Faiz:" to "Interest:",
    "Günlük Kâr" to "Daily Profit",
    "Kasa + Mevduat" to "Cash + Deposit",
    "Rapor Detayı" to "Report Detail",
    "Üretim Tesisleri" to "Production Facilities",
    "Aktif Tesisler" to "Active Facilities",
    "Tümünü Gör" to "View All",
    "Tesis Ekle" to "Add Facility",
    "Sözleşme Oluştur" to "Create Contract",
    "Yatırım Yap" to "Invest",
    "24s En Yüksek" to "24h High",
    "24s En Düşük" to "24h Low",
    "Taban Fiyat" to "Base Price",
    "Piyasa Arzı" to "Market Supply",
    "Sizdeki Stok:" to "Your Stock:",
    "SATIN AL" to "BUY",
    "SAT" to "SELL",
    "Nakit" to "Cash",
    "Net Değer" to "Net Worth",
    "Mevduat" to "Deposit",
    "Kredi" to "Loan",
    "Seviye" to "Level"
)

internal val Dictionary: Map<String, String> = mapOf(
    // SETUP & ONBOARDING
    "LANGUAGE / DİL SEÇİMİ" to "LANGUAGE SELECTION",
    "Lütfen oyunu kullanmak istediğiniz dili seçin:" to "Please select your preferred game language:",
    "Anadolu ticaret pazarında tanınacağınız unvanınızı belirleyin:" to "Choose your trade title to be recognized in the Anatolian market:",
    "Ticaret unvanınızı girin (Örn: Ahi Holding)" to "Enter trade name (e.g. Ahi Holding)",
    "MERKEZ DEPO LOKASYONU" to "CENTRAL WAREHOUSE LOCATION",
    "Lojistik üssünüzü haritadan doğrudan dokunarak seçin:" to "Select your logistics hub directly on the map:",
    "Haritadan şehre dokunun" to "Tap a city on the map",
    "⭐ ÖNERİLEN ÜS" to "⭐ RECOMMENDED BASE",
    "Ekonomik Canlılık" to "Economic Vitality",
    "Üretim Hızı" to "Production Speed",
    "Lojistik" to "Logistics",
    "Sektörler:" to "Sectors:",
    "BAŞLA & REHBERE GEÇ" to "START & OPEN GUIDE",
    "BAŞLA" to "START",
    "GERİ" to "BACK",
    "İLERİ" to "NEXT",
    "Lojistik Merkeziniz" to "Logistics Center",

    // REGIONS
    "Marmara" to "Marmara",
    "Ege" to "Aegean",
    "İç Anadolu" to "Central Anatolia",
    "Akdeniz" to "Mediterranean",
    "Karadeniz" to "Black Sea",
    "Doğu Anadolu" to "Eastern Anatolia",
    "Güneydoğu Anadolu" to "Southeastern Anatolia",
    "Güney Amerika" to "South America",
    "Güneydoğu Asya" to "Southeast Asia",
    "Afrika" to "Africa",
    "Orta Doğu" to "Middle East",
    "Avrupa" to "Europe",
    "Doğu Asya" to "East Asia",
    "Kuzey Amerika" to "North America",
    "Marmara / Ege" to "Marmara / Aegean",

    // COUNTRIES
    "Türkiye" to "Türkiye",
    "Şili" to "Chile",
    "Malezya" to "Malaysia",
    "Güney Afrika" to "South Africa",
    "Irak" to "Iraq",
    "Brezilya" to "Brazil",
    "Almanya" to "Germany",
    "Çin" to "China",
    "Japonya" to "Japan",
    "ABD" to "USA",
    "Hollanda" to "Netherlands",
    "İngiltere" to "United Kingdom",

    // ALL 30 CITIES
    "Eskişehir" to "Eskisehir",
    "Sivas" to "Sivas",
    "Batman" to "Batman",
    "Zonguldak" to "Zonguldak",
    "Artvin" to "Artvin",
    "Muğla" to "Mugla",
    "Elazığ" to "Elazig",
    "Kırıkkale" to "Kirikkale",
    "Kahramanmaraş" to "Kahramanmaras",
    "Konya" to "Konya",
    "Kocaeli" to "Kocaeli",
    "Bursa" to "Bursa",
    "Kayseri" to "Kayseri",
    "Gaziantep" to "Gaziantep",
    "İzmir" to "Izmir",
    "Ankara" to "Ankara",
    "İstanbul" to "Istanbul",
    "Mersin" to "Mersin",
    "Santiago" to "Santiago",
    "Kuala Lumpur" to "Kuala Lumpur",
    "Johannesburg" to "Johannesburg",
    "Basra" to "Basra",
    "Sao Paulo" to "Sao Paulo",
    "Essen" to "Essen",
    "Frankfurt" to "Frankfurt",
    "Şanghay" to "Shanghai",
    "Tokyo" to "Tokyo",
    "Houston" to "Houston",
    "Rotterdam" to "Rotterdam",
    "Londra" to "London",
    "New York" to "New York",
    "Tekirdağ" to "Tekirdag",
    "Çanakkale" to "Canakkale",
    "Şanlıurfa" to "Sanliurfa",

    // CITY PRIMARY PRODUCTS & SPECIALTIES
    "Bor Madeni" to "Boron Mine",
    "Jet Motoru / OSB" to "Jet Engine / OIZ",
    "Demir Cevheri Madeni" to "Iron Ore Mine",
    "Ağır Madencilik" to "Heavy Mining",
    "Ham Petrol Kuyuları" to "Crude Oil Wells",
    "Petrol Sondajı" to "Oil Drilling",
    "Taş Kömürü Madeni" to "Hard Coal Mine",
    "Ağır Metalürji" to "Heavy Metallurgy",
    "Bakır Cevheri Madeni" to "Copper Ore Mine",
    "Maden Havzası" to "Mining Basin",
    "Kuvars / Silisyum Ocağı" to "Quartz / Silicon Quarry",
    "Kireçtaşı" to "Limestone",
    "Krom Cevheri Madeni" to "Chromium Ore Mine",
    "Metal Madenciliği" to "Metal Mining",
    "Kükürt & Sanayi Kimyası" to "Sulfur & Industrial Chemistry",
    "Kimyasal Hammadde" to "Chemical Raw Materials",
    "Endüstriyel Pamuk Tarlaları" to "Industrial Cotton Fields",
    "Tekstil Hammaddesi" to "Textile Raw Materials",
    "Boksit Madeni" to "Bauxite Mine",
    "Alüminyum Döküm" to "Aluminum Casting",
    "Petrokimya" to "Petrochemicals",
    "Sentetik Elyaf Sanayii" to "Synthetic Fiber Industry",
    "Kablo, Döküm & Profil Sanayii" to "Cabling, Casting & Profiles",
    "Otomotiv Yan Sanayi" to "Auto Sub-Industry",
    "Paslanmaz Çelik & Alaşım Sanayii" to "Stainless Steel & Alloys",
    "Endüstriyel Cihaz" to "Industrial Equipment",
    "Endüstriyel Kimya & Dokuma Sanayii" to "Industrial Chemistry & Weaving",
    "Ambalaj" to "Packaging",
    "Çip, Yarı İletken & Sensör Sanayii" to "Chips, Semiconductors & Sensors",
    "Fiber Optik" to "Fiber Optics",
    "Savunma Sanayii, Radar & Kompozit Gövde" to "Defense, Radar & Composite Hull",
    "Havacılık" to "Aerospace",
    "Elektrikli Araç, Uydu/İHA ve Borsa Merkezi" to "EV, Satellite/UAV & Stock Exchange Hub",
    "Mega Teknoloji" to "Mega Technology",
    "Mega Akdeniz Tersanesi & Lojistik Kapısı" to "Mega Mediterranean Shipyard & Gateway",
    "Deniz Ticareti" to "Maritime Trade",
    "Lityum Ekstraksiyon Tesisi" to "Lithium Extraction Plant",
    "Maden" to "Mining",
    "Doğal Kauçuk Plantasyonu" to "Natural Rubber Plantation",
    "Lateks İşleme" to "Latex Processing",
    "Platin & Değerli Metal Madeni" to "Platinum & Precious Metals Mine",
    "Grafit & Nadir Element" to "Graphite & Rare Elements",
    "Ağır Ham Petrol Sondaj Kulesi" to "Heavy Crude Oil Rig",
    "Doğal Gaz" to "Natural Gas",
    "Biyo-Etanol" to "Bio-Ethanol",
    "Biyo-Plastik & Polimer" to "Bio-Plastics & Polymers",
    "Ağır Sanayi Alman Çeliği Fabrikası" to "Heavy Industry German Steel Plant",
    "Metalürji" to "Metallurgy",
    "Otomotiv Yürür Aksam & Şasi Tesisi" to "Automotive Drivetrain & Chassis Plant",
    "Mekanik" to "Mechanics",
    "Giga Batarya Fabrikası" to "Giga Battery Factory",
    "Enerji Depolama" to "Energy Storage",
    "Hassas Robotik Kol" to "Precision Robotics Arm",
    "Otomasyon Sanayii" to "Automation Industry",
    "Kaya Gazı" to "Shale Gas",
    "Uzay Roketi Sanayii" to "Space Rocket Industry",
    "Yenilenebilir Enerji" to "Renewable Energy",
    "Rüzgar Türbini Kompleksi" to "Wind Turbine Complex",
    "Ağır İş Makinesi Fabrikası" to "Heavy Machinery Plant",
    "Dünya Borsa Merkezi" to "Global Stock Exchange Center",
    "Wall Street Finans & Dünya Borsası" to "Wall Street Finance & Global Stock Exchange",
    "Kuantum Bilişim & AI Veri Merkezi" to "Quantum Computing & AI Datacenter",
    "Biyofarmasötik Laboratuvarı" to "Biopharmaceutical Laboratory",

    // LOGISTICS ITEMS
    "Yüksek Hızlı Tren" to "High-Speed Rail",
    "Otoyol" to "Highway",
    "Havalimanı" to "Airport",
    "Demiryolu" to "Railway",
    "Karayolu" to "Roadway",
    "Liman" to "Seaport",
    "Boru Hattı" to "Pipeline",
    "Liman Bağlantısı" to "Port Link",
    "Mega Liman" to "Mega Seaport",
    "Pasifik Liman Bağlantısı" to "Pacific Port Link",
    "Malakka Boğazı Limanı" to "Strait of Malacca Port",
    "Körfez Limanı" to "Gulf Seaport",
    "Boru Hatları" to "Pipelines",
    "Santos Limanı" to "Port of Santos",
    "Ren Nehri Limanı" to "Rhine River Port",
    "Demiryolu Ağı" to "Railway Network",
    "Havalimanı Hub" to "Airport Hub",
    "Otoyol Kavşağı" to "Highway Junction",
    "Dünyanın En Büyük Limanı" to "World's Largest Port",
    "Tokyo Körfezi Limanı" to "Tokyo Bay Port",
    "Houston Uzay Üssü" to "Houston Space Base",
    "Meksika Körfezi Limanı" to "Gulf of Mexico Port",
    "Avrupa'nın En Büyük Limanı" to "Europe's Largest Port",
    "Kanallar" to "Canals",
    "Heathrow Hub" to "Heathrow Hub",
    "Thames Lojistik" to "Thames Logistics",
    "JFK Havalimanı Hub" to "JFK Airport Hub",
    "New York & New Jersey Limanı" to "Port of New York & New Jersey",
    "Atlantik Deniz Koridoru" to "Atlantic Sea Corridor",

    // CITY DESCRIPTIONS
    "Türkiye'nin bor rezervi merkezi ve havacılık/jet motoru sanayii üssü." to "Türkiye's boron reserve hub and aerospace/jet engine industrial base.",
    "Sivas demir yatakları ve Cumhuriyet'in demiryolu/ağır sanayi kavşağı." to "Sivas iron deposits and railway/heavy industry junction.",
    "Raman Dağı petrol sahaları ve Türkiye'nin ilk petrol rafineri merkezi." to "Raman Mountain oil fields and Türkiye's first oil refinery center.",
    "Karaelmas havzası. Çelik endüstrisinin can damarı taş kömürü rezervleri." to "Black diamond basin. Hard coal reserves powering the steel industry.",
    "Artvin zengin bakır yatakları ve Doğu Karadeniz maden havzası." to "Artvin's rich copper deposits and Eastern Black Sea mining basin.",
    "Muğla kuvars ve silisyum ocakları; cam ve yarı iletken hammaddesi kaynağı." to "Mugla quartz and silicon quarries; source of glass and semiconductor feedstock.",
    "Elazığ krom sahaları ve zengin yer altı madencilik kompleksi." to "Elazig chromium fields and rich underground mining complex.",
    "Kimya ve hammadde endüstrisi, sanayi tuzu ve kükürt üretim merkezi." to "Chemical and raw materials industry, industrial salt and sulfur production hub.",
    "Verimli tarım ovaları ve Türkiye'nin en büyük pamuk üretim havzalarından biri." to "Fertile agricultural plains and one of Türkiye's largest cotton basins.",
    "Konya boksit yatakları ve entegre alüminyum izabe/döküm tesisleri." to "Konya bauxite deposits and integrated aluminum smelter/casting plants.",
    "Tüpraş rafinerisi, polimer tesisleri ve ileri sentetik dokuma kimyası." to "Refinery, polymer plants, and advanced synthetic weaving chemistry.",
    "Kablo üretimi, metal profil döküm ve otomotiv yedek parça üssü." to "Cabling production, metal profile casting, and automotive spare parts base.",
    "Paslanmaz çelik haddehaneleri, titanyum alaşım ve beyaz eşya sanayisi." to "Stainless steel rolling mills, titanium alloys, and home appliances industry.",
    "Dokuma, endüstriyel iplik, polimerik ambalaj ve ihracat sanayii." to "Weaving, industrial yarns, polymeric packaging, and export industry.",
    "Yarı iletken çip üretim tesisleri, silisyum wafer ve optik sensör kompleksi." to "Semiconductor chip fabs, silicon wafers, and optical sensor complex.",
    "Milli savunma sanayiinin kalbi. Radar, karbon kompozit ve İHA gövdeleri." to "Heart of defense industry. Radar, carbon composites, and UAV fuselages.",
    "Borsa İstanbul finans üssü, elektrikli otomobil fabrikaları ve uydu geliştirme merkezi." to "Borsa Istanbul financial hub, electric vehicle gigafactories, and satellite center.",
    "Akdeniz'in en büyük konteyner limanı, süperyat ve kargo gemisi tersaneleri." to "Mediterranean's largest container port, superyacht, and cargo shipyards.",
    "And Dağları eteklerindeki dünyanın en büyük lityum havzası ve ekstraksiyon tesisi." to "World's largest lithium basin and extraction facility at the foot of the Andes.",
    "Güneydoğu Asya'nın devasa doğal kauçuk plantasyonları ve polimer merkezleri." to "Southeast Asia's massive natural rubber plantations and polymer hubs.",
    "Afrika kıtasının en zengin platin, grafit ve nadir toprak elementleri madenleri." to "African continent's richest platinum, graphite, and rare earth mines.",
    "Basra Körfezi mega petrol sahaları ve ağır ham petrol sondaj kuleleri." to "Persian Gulf mega oil fields and heavy crude drilling rigs.",
    "Latin Amerika'nın biyo-yakıt ve sürdürülebilir biyo-plastik polimer sanayi devi." to "Latin America's bio-fuel and sustainable bio-plastic polymer giant.",
    "Essen bölgesi ağır endüstrisi, yüksek dayanımlı Alman çeliği ve alaşım dökümhaneleri." to "Essen heavy industry, high-strength German steel, and alloy foundries.",
    "Avrupa otomotiv yan sanayii omurgası, yürür aksam, şasi ve robotik montaj hatları." to "European automotive supply backbone, drivetrains, chassis, and robotics lines.",
    "Küresel enerji devrimi merkezi. Lityum-iyon ve nano grafen giga batarya fabrikaları." to "Global energy revolution center. Li-ion and nano-graphene battery gigafactories.",
    "Hassas robotik kollar, endüstriyel otomasyon ve otonom drone sürü sistemleri." to "Precision robotics arms, industrial automation, and autonomous drone swarm systems.",
    "NASA Uzay Merkezi ve derin uzay roket teknolojileri, kaya gazı işleme kompleksleri." to "NASA Space Center, deep-space rocket technologies, and shale gas complexes.",
    "Kuzey Denizi açık deniz rüzgar türbinleri, hidrojen elektroliz santralleri ve yeşil şebeke." to "North Sea offshore wind turbines, hydrogen electrolysis plants, and green grid.",
    "Dünya finans başkenti, ağır madencilik iş makineleri ve yüksek hızlı tren mühendisliği." to "World financial capital, heavy mining machinery, and high-speed rail engineering.",
    "Dünya finans ve ticaretinin küresel merkezi. Wall Street borsası, Manhattan kuantum süper bilgisayarları, AI veri merkezleri ve ileri biyofarmasötik sanayii." to "Global center of world finance and trade. Wall Street stock exchange, Manhattan quantum supercomputers, AI datacenters, and advanced biopharmaceutical industry.",

    // ALL PRODUCTS (RAW, INTERMEDIATE, END-PRODUCTS, MEGA)
    "Demir Cevheri" to "Iron Ore",
    "Bakır" to "Copper Ore",
    "Silisyum" to "Silicon Ore",
    "Alüminyum" to "Aluminum Ore",
    "Kömür" to "Coal",
    "Kireçtaşı" to "Limestone",
    "Lityum Cevheri" to "Lithium Ore",
    "Kereste Odunu" to "Lumber Timber",
    "Kimyasal Hammadde" to "Chemical Raw Materials",
    "Ham Petrol" to "Crude Oil",
    "Doğalgaz" to "Natural Gas",
    "Titanyum Cevheri" to "Titanium Ore",
    "Grafit & Nadir Element" to "Graphite & Rare Earth",
    "Doğal Kauçuk" to "Natural Rubber",
    "Endüstriyel Pamuk" to "Industrial Cotton",
    "Çelik" to "Refined Steel",
    "Kablo" to "Copper Cabling & Wire",
    "Cam & Optik" to "Glass & Optics",
    "İplik & Kumaş" to "Yarn & Fabric",
    "Enerji Aküsü" to "Energy Battery",
    "Plastik & Polimer" to "Plastics & Polymers",
    "İşlenmiş Kereste" to "Processed Lumber",
    "Çimento" to "Portland Cement",
    "İşlenmiş Akaryakıt" to "Refined Fuel",
    "Otomotiv Lastiği" to "Automotive Tires",
    "Endüstriyel Ambalaj" to "Industrial Packaging",
    "Külçe Alüminyum" to "Aluminum Ingot",
    "Sıvılaştırılmış Gaz (LNG)" to "Liquefied Gas (LNG)",
    "Külçe Titanyum" to "Titanium Ingot",
    "Devre Kartı Altyapısı (PCB)" to "PCB Substrate",
    "Sentetik Kompozit Elyaf" to "Synthetic Composite Fiber",
    "Alaşımlı Titanyum Levha" to "Titanium Alloy Sheet",
    "Karbon Elyaf Kompozit" to "Carbon Fiber Composite",
    "Yarı İletken Silisyum Wafer" to "Semiconductor Silicon Wafer",
    "Fiber Optik İletişim Kablosu" to "Fiber Optic Cable",
    "Grafen Nano Tabaka" to "Graphene Nano Sheet",
    "Mikroçip" to "Microchip",
    "Akıllı Telefon & Terminal" to "Smartphone & Terminal",
    "Endüstriyel Üniforma & Koruyucu Giyim" to "Industrial Uniform & Workwear",
    "Oto Parçası & Mekaniği" to "Auto Parts & Mechanics",
    "Endüstriyel Cihaz & Beyaz Eşya" to "Industrial Appliances & White Goods",
    "Modüler Donanım & Mobilya" to "Modular Hardware & Furniture",
    "Yapı & İnşaat Elemanı" to "Building & Construction Element",
    "İlaç & Biyo-Kimya" to "Pharmaceuticals & Biochemistry",
    "Ağır İş Makinesi" to "Heavy Construction Machinery",
    "Güneş Enerjisi Paneli" to "Solar Energy Panel",
    "Petrokimya & Madeni Yağ" to "Petrochemicals & Lubricants",
    "Medikal Cihaz & Biyoteknoloji" to "Medical Devices & Biotech",
    "Ağır Türbin & Jet Motoru" to "Heavy Turbine & Jet Engine",
    "Lojistik Konteyner Sistemi" to "Logistics Container System",
    "Havacılık Sınıfı Kompozit Panel" to "Aerospace Grade Composite Panel",
    "Endüstriyel Robot Kolu & Otomasyon" to "Industrial Robotic Arm & Automation",
    "5G/6G Baz İstasyonu & Telekom Modülü" to "5G/6G Base Station & Telecom Module",
    "Nano Grafen Güç Hücresi" to "Nano Graphene Power Cell",
    "Elektrikli Otomobil" to "Electric Vehicle (EV)",
    "Otonom İHA / SİHA Sistemleri" to "Autonomous UAV / Drone Systems",
    "Uydu & İletişim Modülü" to "Satellite & Communication Module",
    "Konteyner Gemisi & Şilep" to "Container Cargo Ship",
    "Yüksek Hızlı Tren Seti" to "High-Speed Train Set",
    "AI Sunucu Kompleksi" to "AI Data Center Server Complex",
    "Askeri Korvet & Fırkateyn" to "Naval Defense Frigate & Corvette",
    "Yeşil Hidrojen Üretim Santrali" to "Green Hydrogen Production Plant",
    "Akıllı Şehir Enerji Şebekesi" to "Smart City Energy Grid",
    "Lüks Süper Yat" to "Luxury Super Yacht",
    "Uzay Roketi & İtki Sistemi" to "Space Rocket & Propulsion System",
    "Akıllı Gökdelen & Mega Kompleks" to "Smart Skyscraper & Mega Complex",
    "Füzyon Reaktör Çekirdeği" to "Fusion Reactor Core",
    "Kuantum Süper Bilgisayar" to "Quantum Supercomputer",
    "Otonom İHA / SİHA Sürüsü" to "Autonomous UAV / Commercial Drone Swarm",
    "Hyperloop Yolcu Kapsülü" to "Hyperloop Passenger Capsule",
    "VIP Uçak İç Kabin Tasarımı" to "VIP Aircraft Interior Outfit",

    // ALL FACILITIES
    "Demir Madeni" to "Iron Mine",
    "Bakır Madeni" to "Copper Mine",
    "Silisyum Madeni" to "Silicon Mine",
    "Alüminyum Madeni" to "Aluminum Mine",
    "Alüminyum Ocağı" to "Aluminum Quarry",
    "Kömür Madeni" to "Coal Mine",
    "Kireçtaşı Ocağı" to "Limestone Quarry",
    "Lityum Madeni" to "Lithium Mine",
    "Lityum Ocağı" to "Lithium Quarry",
    "Kereste Kampı" to "Timber Camp",
    "Orman Sahası" to "Timber Forest Area",
    "Kimya Tesisi" to "Chemical Plant",
    "Petrol Kuyusu" to "Oil Well",
    "Doğalgaz Kuyusu" to "Natural Gas Well",
    "Titanyum Madeni" to "Titanium Mine",
    "Grafit Madeni" to "Graphite Mine",
    "Kauçuk Üretim Merkezi" to "Rubber Production Center",
    "Pamuk Tarlası" to "Cotton Field",
    "Çelik Haddahanesi" to "Steel Mill & Foundry",
    "Kablo Fabrikası" to "Cable Factory",
    "Cam & Optik Fabrikası" to "Glass & Optics Plant",
    "Tekstil & Dokuma Fabrikası" to "Textile & Weaving Plant",
    "Akü & Enerji Fabrikası" to "Battery & Energy Plant",
    "Plastik Fabrikası" to "Plastic Factory",
    "Kereste Fabrikası" to "Sawmill & Lumber Plant",
    "Çimento Fabrikası" to "Cement Factory",
    "Rafineri" to "Petroleum Refinery",
    "Lastik Fabrikası" to "Tire Factory",
    "Ambalaj Fabrikası" to "Packaging Factory",
    "Alüminyum Dökümhanesi" to "Aluminum Smelter & Foundry",
    "Gaz Tesisleri" to "Gas Processing Plant",
    "Titanyum Döküm Tesisi" to "Titanium Smelting Plant",
    "PCB Üretim Tesisi" to "PCB Electronics Plant",
    "Sentetik Elyaf Fabrikası" to "Synthetic Fiber Mill",
    "Karbon Elyaf Üretim Tesisi" to "Carbon Fiber Weaving Plant",
    "Wafer Üretim Kompleksi" to "Silicon Wafer Foundry",
    "Fiber Optik Fabrikası" to "Fiber Optics Plant",
    "Grafen Üretim Kompleksi" to "Graphene Advanced Materials Plant",
    "Çip Fabrikası" to "Microchip Foundry",
    "Telefon Fabrikası" to "Smartphone Assembly Plant",
    "Konfeksiyon" to "Apparel & Garment Factory",
    "Oto Yan Sanayi" to "Automotive Parts Plant",
    "Beyaz Eşya Fabrikası" to "Home Appliances Plant",
    "Mobilya Fabrikası" to "Furniture Factory",
    "Yapı Malzemeleri Tesisleri" to "Construction Materials Plant",
    "İlaç Fabrikası" to "Pharmaceuticals Lab & Plant",
    "Makine Fabrikası" to "Heavy Machinery Plant",
    "Güneş Paneli Fabrikası" to "Solar Panel Gigafactory",
    "Petrokimya Kompleksi" to "Petrochemical Complex",
    "Medikal Teknoloji Tesisleri" to "Medical Tech Plant",
    "Türbin & Motor Fabrikası" to "Turbine & Jet Engine Plant",
    "Konteyner Üretim Tesisleri" to "Container Manufacturing Facility",
    "Aero-Kompozit Üretim Tesisi" to "Aerospace Composite Plant",
    "Robotik Otomasyon Fabrikası" to "Robotics & Automation Plant",
    "Telekomünikasyon Sistemleri Fabrikası" to "Telecom Systems Plant",
    "Nano Pil Gigafactory" to "Graphene Nano Battery Gigafactory",
    "Elektrikli Araç Gigafactory" to "Electric Vehicle Gigafactory",
    "Havacılık & İHA Fabrikası" to "Aerospace & UAV Plant",
    "Uzay & Uydu Teknolojileri Kompleksi" to "Space & Satellite Complex",
    "Tersane Kompleksi" to "Shipyard Complex",
    "Demiryolu Sanayi Kompleksi" to "Railway Industry Complex",
    "Yapay Zeka & Veri Merkezi Tesisi" to "AI Supercomputer Data Center",
    "Askeri Tersane Kompleksi" to "Naval Defense Shipyard",
    "Hidrojen Santrali Kompleksi" to "Hydrogen Energy Complex",
    "Akıllı Şehir Şebeke Kompleksi" to "Smart City Grid Center",
    "Lüks Yat Tersanesi" to "Luxury Yacht Shipyard",
    "Uzay Fırlatma & Roket Kompleksi" to "Space Launch & Rocket Complex",
    "Mega Yapı İnşaat Kompleksi" to "Smart Mega Construction Hub",
    "Füzyon Enerji Kompleksi" to "Fusion Energy Complex",
    "Kuantum Teknoloji Kompleksi" to "Quantum Tech Complex",
    "İHA & Otonom Sistemler Fabrikası" to "Autonomous Systems & Drone Swarm Plant",
    "Hyperloop Mega Fabrikası" to "Hyperloop Mega Factory",
    "VIP Kabin & İklimlendirme Kompleksi" to "VIP Aircraft Interiors Facility",

    // TECH TREE & R&D
    "YEŞİL ENERJİ VE İKLİM" to "GREEN ENERGY & CLIMATE",
    "UZAY VE SAVUNMA SANAYİİ" to "AEROSPACE & SPACE DEFENSE",
    "KUANTUM VE YAPAY ZEKA" to "QUANTUM & AI",
    "AĞIR SANAYİ VE MAKİNE" to "HEAVY INDUSTRY & MACHINERY",
    "BİYOTEKNOLOJİ VE İLAÇ" to "BIOTECH & PHARMA",
    "TÜKETİCİ ELEKTRONİĞİ" to "CONSUMER ELECTRONICS",
    "PETROKİMYA VE RAFİNERİ" to "PETROCHEMICALS & REFINERY",
    "OTOMATİK KALİTE KONTROL" to "AUTO QUALITY CONTROL",
    "OTOMATİK LOJİSTİK YAZILIMI" to "AUTO LOGISTICS SOFTWARE",
    "AKILLI OTOMASYON" to "SMART AUTOMATION",
    "NANO-MATERYAL ÜRETİMİ" to "NANO-MATERIAL PRODUCTION",
    "SİBER GÜVENLİK VE VERİ" to "CYBER SECURITY & DATA",

    // UI LABELS & DIALOGS
    "Mevcut Bakiye:" to "Current Balance:",
    "Pazar Hacmi:" to "Market Volume:",
    "Birim Üretim Maliyeti:" to "Unit Production Cost:",
    "Tahmini Üretim Süresi:" to "Est. Production Time:",
    "Maksimum Üretim Limiti:" to "Max Production Limit:",
    "Toplam Tesis Yatırımı:" to "Total Facility Investment:",
    "Geri İade Oranı:" to "Refund Rate:",
    "Geri Alınacak Nakit:" to "Cash Recoverable:",
    "Bölgesel Çarpan:" to "Regional Multiplier:",
    "İnşa Bedeli:" to "Build Cost:",
    "Çıktı:" to "Output:",
    "Eşzamanlı Araştırma (Maks 4 Slot)" to "Concurrent Research (Max 4 Slots)",
    "Aktif Araştırma Slotları" to "Active Research Slots",
    "Araştırma Yap" to "Research",
    "Hızlandır" to "Speed Up",
    "Sözleşmeyi Karşıla" to "Fulfill Contract",
    "İptal Et" to "Cancel",
    "Talep Aç" to "Create Request",
    "İlanı Yayınla" to "Publish Listing",
    "Alım Emri Yayınla" to "Publish Buy Order",
    "Müzayedeyi Başlat" to "Start Auction",
    "Satın Alımı Onayla" to "Confirm Purchase",
    "Mevcut Kredi Borcu:" to "Current Loan Debt:",
    "Geri Ödeme Yap" to "Make Repayment",
    "Kredi Çek" to "Take Loan",
    "Mevduat Yatır" to "Deposit Money",
    "Mevduat Çek" to "Withdraw Deposit",
    "Borsa Hisseleri" to "Exchange Equities",
    "Halka Arz" to "IPO & Offerings",
    "Hisse Fiyatı" to "Share Price",
    "Piyasa Değeri" to "Market Capitalization",
    "Halka Açıklık Oranı" to "Public Float Ratio",
    "Temettü Dağıt" to "Distribute Dividends",
    "Hisse Geri Alımı" to "Share Buyback",
    "Ek Hisse Satışı" to "Additional Share Sale",
    "Hisse Senedi Al" to "Buy Shares",
    "Hisse Senedi Sat" to "Sell Shares",
    "Şirket Kasası" to "Company Treasury",
    "Şirket Değeri" to "Company Valuation",
    "Holding Ligi" to "Conglomerate League",
    "Aylık Sıralama" to "Monthly Rankings",
    "Ticaret Odaları" to "Chambers of Commerce",
    "Müze & Prestij" to "Museum & Prestige",
    "Koleksiyon" to "Collection",
    "Müzayede" to "Auction",
    "Milli Konsorsiyum" to "National Consortium",
    "Tedarikçi Slotları" to "Supplier Slots",
    "Seri Üretim" to "Mass Production",
    "Konsorsiyum Kur" to "Form Consortium",
    "Konsorsiyuma Katıl" to "Join Consortium",
    "Test Üretimi" to "Test Production",
    "Kâr Payı Dağıtımı" to "Dividend Distribution",
    "Kurucu Yönetim Payı" to "Founder Management Share",
    "Tedarikçi Katkı Hissesi" to "Supplier Contribution Share",
    "Marka Primi" to "Brand Premium",
    "SLA Darboğaz Koruması" to "SLA Bottleneck Protection",
    "Darboğazı Devral" to "Take Over Bottleneck",
    "Sohbet & Koordinasyon" to "Chat & Coordination",
    "Sistem Mesajları" to "System Messages",

    // COUNTRIES & REGIONS
    "Türkiye" to "Türkiye",
    "Şili" to "Chile",
    "Malezya" to "Malaysia",
    "Güney Afrika" to "South Africa",
    "Irak" to "Iraq",
    "Brezilya" to "Brazil",
    "Almanya" to "Germany",
    "Çin" to "China",
    "Japonya" to "Japan",
    "ABD" to "USA",
    "Hollanda" to "Netherlands",
    "İngiltere" to "United Kingdom",
    "İç Anadolu" to "Central Anatolia",
    "Marmara" to "Marmara",
    "Ege" to "Aegean",
    "Akdeniz" to "Mediterranean",
    "Karadeniz" to "Black Sea",
    "Doğu Anadolu" to "Eastern Anatolia",
    "Güneydoğu Anadolu" to "Southeastern Anatolia",
    "Güney Amerika" to "South America",
    "Güneydoğu Asya" to "Southeast Asia",
    "Afrika" to "Africa",
    "Orta Doğu" to "Middle East",
    "Avrupa" to "Europe",
    "Doğu Asya" to "East Asia",
    "Kuzey Amerika" to "North America",

    // FACILITY & CITY FILTERING DIALOGS
    "Yatırım Yapılacak Şehri Seçin" to "Select City for Investment",
    "Uygun Şehir" to "Eligible Cities",
    "Kurulumu" to "Construction",
    "Uygun Şehirler:" to "Eligible Cities:",
    "Bu şehre özgü kurulabilir tesisler listeleniyor." to "Listing facilities eligible for this city's geological & industrial profile.",
    "Bu tesis yalnızca jeolojik ve sanayi altyapısı uygun şehirlerde kurulabilir. Her şehrin maliyet çarpanı altyapısına göre değişir." to "This facility can only be built in cities with suitable geological and industrial infrastructure. Regional cost multipliers apply.",
    "Bu şehirde kurulabilecek açık tesis bulunmuyor. Ar-Ge merkezinde yeni teknolojiler araştırın veya diğer şehirleri inceleyin." to "No unlocked facilities available for this city. Research new technologies in R&D or explore other cities.",
    "Aramanıza uygun tesis bulunamadı." to "No matching facility found.",
    "tesisi bu şehre kurulamaz! Yalnızca şu şehirlerde kurulabilir:" to "facility cannot be built in this city! Eligible cities:",
    "Depo Doluluk Oranı" to "Warehouse Occupancy Rate",
    "BİLDİRİM AKIŞI" to "NOTIFICATION FEED",
    "Aktif Tesisler (\${productionProgress.size})" to "Active Facilities (\${productionProgress.size})",
    "(Boş: \$remainingCap Ton)" to "(Empty: \$remainingCap Tons)",
    "AKTİF" to "ACTIVE",
    "Borsa" to "Stock Market",
    "Ton" to "Tons",
    "Detaylı Envanter >" to "Detailed Inventory >",
    "Piyasa Değeri" to "Market Value",
    "CANLI BİLDİRİM" to "LIVE NOTIFICATION",
    "Şu an üretim yapan tesisiniz yok." to "You have no facilities currently in production.",
    "Tüm sistemler normal ve operasyonlar aktif." to "All systems normal and operations active.",
    "CANLI PİYASA RADARI" to "LIVE MARKET RADAR",
    "YENİ" to "NEW",
    "Geçmiş" to "History",
    "EN DEĞERLİ VARLIKLAR" to "MOST VALUABLE ASSETS",
    "ARAMAYA UYGUN TESİS BULUNAMADI" to "NO FACILITIES FOUND FOR SEARCH",
    "Sat" to "Sell",
    "MAKS SEVİYE" to "MAX LEVEL",
    "Varlıklar ekranından bakım yapabilirsiniz." to "You can perform maintenance from the Assets screen.",
    "⚠️ Dikkat: Satış sonrasında tesis haritadan ve bilançonuzdan tamamen silinir." to "⚠️ Attention: After sale, the facility will be completely removed from the map and your balance sheet.",
    "Lütfen geçerli miktar veya yeterli hammadde sağlayın!" to "Please provide a valid amount or sufficient raw materials!",
    "VAZGEÇ" to "CANCEL",
    "TOPLAM MALİYET:" to "TOTAL COST:",
    "İnşa Bedeli: " to "Build Cost: ",
    "sn kaldı" to "s left",
    "YENİ TESİS KUR" to "BUILD NEW FACILITY",
    "TESİSİ SAT" to "SELL FACILITY",
    "Yoldaki Lojistik Sevkiyatlar" to "Logistics Shipments in Transit",
    "Boşta" to "Idle",
    "Üretim Yap" to "Produce",
    "TESİSİ TASFİYE ET" to "LIQUIDATE FACILITY",
    "YATIRIM FIRSATI" to "INVESTMENT OPPORTUNITY",
    "Adet" to "Units",
    "dk" to "min",
    "Kurulumu" to "Construction",
    "Detay" to "Details",
    "Maksimum Üretim Limiti:" to "Max Production Limit:",
    "Üretim yavaşlıyor" to "Production is slowing down",
    "HIZLANDIR" to "SPEED UP",
    "Sanayi kataloğundan tesis türünü seçin" to "Select facility type from the industrial catalog",
    "Üretimi" to "Production",
    "Kalan:" to "Remaining:",
    "AKTİF ŞEHİR" to "ACTIVE CITY",
    "HENÜZ BİR TESİSİNİZ YOK" to "YOU DON'T HAVE A FACILITY YET",
    "AR-GE'DE ARAŞTIR" to "RESEARCH IN R&D",
    "ÜRETİLİYOR" to "PRODUCING",
    "Tüm Kademeler" to "All Tiers",
    "Geri Alınacak Nakit:" to "Recoverable Cash:",
    "Çıktı: " to "Output: ",
    "Tesis / Ürün adı ara..." to "Search facility / product...",
    "Arama terimini değiştirebilir veya filtreleri temizleyebilirsiniz." to "You can change the search term or clear filters.",
    "Aktif" to "Active",
    "Yıpranma:" to "Wear:",
    "Yeni Tesis Ekle" to "Add New Facility",
    "Kondisyon: %100" to "Condition: 100%",
    "Yatırım Yapılacak Şehri Seçin" to "Select City to Invest",
    "Üretimi Başlat" to "Start Production",
    "Tesis" to "Facility",
    "Birim Üretim Maliyeti (Borsa Endeksli):" to "Unit Production Cost (Market Indexed):",
    "Üretim Miktarı (Adet)" to "Production Quantity (Units)",
    "SAHİP OLUNAN TESİSLER VE SEVİYELER" to "OWNED FACILITIES AND LEVELS",
    "Tahmini Üretim Süresi:" to "Estimated Production Time:",
    "İptal" to "Cancel",
    "Tesis Yıpranması:" to "Facility Wear:",
    "Eksik Hammaddeleri Borsadan Al" to "Buy Missing Raw Materials from Market",
    "Bakım" to "Maintenance",
    "Tahmini Satış:" to "Est. Sales:",
    "Tüm Şehirler" to "All Cities",
    "Üretim imparatorluğunuzu kurmak için hemen yeni bir tesis inşa edebilirsiniz." to "You can build a new facility right now to start your production empire.",
    "ÜRETİM HATTI" to "PRODUCTION LINE",
    "Seviye" to "Level",
    "Bu tesis yalnızca jeolojik ve sanayi altyapısı uygun şehirlerde kurulabilir. Her şehrin maliyet çarpanı altyapısına göre değişir." to "This facility can only be built in cities with suitable geological and industrial infrastructure. Regional multipliers apply.",
    "MÜLKÜNÜZDE" to "OWNED",
    "Uygun Şehir" to "Eligible City",
    "GEREKLİ HAMMADDELER (GİRDİ):" to "REQUIRED RAW MATERIALS (INPUT):",
    "TOPLAM TESİS" to "TOTAL FACILITIES",
    "Geri İade Oranı:" to "Refund Rate:",
    "İnşa Et" to "Build",
    "Gizle" to "Hide",
    "Nakit İade" to "Cash Refund",
    "Toplam Tesis Yatırımı:" to "Total Facility Investment:",
    "Enflasyon: %\${inflation} | Faiz: %\${String.format(\"%.1f\", macroState.centralBankInterestRate)}" to "Inflation: %\${inflation} | Interest: %\${String.format(\"%.1f\", macroState.centralBankInterestRate)}",
    "Pazar verileri güncelleniyor..." to "Market data updating...",
    "Yenile" to "Refresh",
    "ŞİRKET KASASI" to "COMPANY TREASURY",
    "Mevcut Bakiye" to "Current Balance",
    "PAZAR HACMİ" to "MARKET VOLUME",
    "\$totalListingsCount Aktif Teklif" to "\$totalListingsCount Active Offers",
    "İLANLARINIZ" to "YOUR LISTINGS",
    "\${myActiveListings.size} İlan" to "\${myActiveListings.size} Listings",
    "Yayındaki Teklif" to "Active Offers",
    "İlan" to "Listings",
    "Aktif Teklif" to "Active Offers",
    "Ürün, şirket veya şehir ara..." to "Search product, company, or city...",
    "Tüm Tier'lar" to "All Tiers",
    "🌾 Tier 1" to "🌾 Tier 1",
    "🏭 Tier 2" to "🏭 Tier 2",
    "📱 Tier 3" to "📱 Tier 3",
    "🚀 Tier 4" to "🚀 Tier 4",
    "Pazarda Teklif Bulunmuyor" to "No Offers in the Market",
    "Aramaya Uygun İlan Yok" to "No Listings Found",
    "Şu anda diğer üreticiler tarafından yayınlanmış aktif teklif yok. Kendi ürünlerinizi pazara sunabilirsiniz!" to "No active offers from other manufacturers. You can publish your own products to the market!",
    "Arama kriterlerinizi değiştirerek veya filtreleri temizleyerek tekrar deneyebilirsiniz." to "You can try again by changing your search criteria or clearing filters.",
    "Pazara sunulan stoğunuz depolarınızdan düşülür" to "Stock offered to the market is deducted from your warehouses",
    "Aktif Satış İlanınız Yok" to "You Have No Active Sale Listings",
    "Depolarınızdaki fazla ham madde veya işlenmiş ürünleri B2B pazarda diğer oyunculara satarak nakit akışı sağlayabilirsiniz." to "You can generate cash flow by selling excess raw materials or processed products from your warehouses to other players in the B2B market.",
    "İlan başarıyla iptal edildi ve ürünler depoya iade edildi." to "Listing successfully cancelled and products returned to warehouse.",
    "Vadeli B2B Sözleşmeleri" to "B2B Futures Contracts",
    "Fiyat dalgalanmalarına karşı sigortalı tedarik zinciri" to "Supply chain insured against price fluctuations",
    "Yeni Sözleşme" to "New Contract",
    "Aktif Vadeli Sözleşme Yok" to "No Active Futures Contracts",
    "Piyasada henüz yayınlanmış bir vadeli sözleşme bulunmuyor. İlk sözleşmeyi siz imzalayabilirsiniz." to "No futures contracts published in the market yet. You can sign the first contract.",
    "Müzayede Başlat" to "Start Auction",
    "Müzayedeye çıkarılacak deponuzda ürün bulunmuyor." to "No products in your warehouse to put up for auction.",
    "Ürün Seçin:" to "Select Product:",
    "Aynı Şehir Teslimat" to "Same City Delivery",
    "Teslimat Dahil Toplam" to "Total Including Delivery",
    "Aynı Şehir (Ücretsiz Teslim)" to "Same City (Free Delivery)",
    "Satın Al" to "Buy"
)
